[package]
name = "benckmark_memcached_redis"
version = "0.1.0"
authors = ["Gabriel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memcache = "0.14.0"
uuid =  { version="0.8.1", features = ["v4"] }
